### ISSUE TITLE
Add mlr3resampling to mlr_reflections$loaded_packages

### ISSUE THREAD

**Issue by be-marc** [tdhock/mlr3resampling#17]
Hey,

there was a problem with extra column roles and parallelization. You should add ` x$loaded_packages = c(x$loaded_packages, "mlr3resampling")` to zzz.R after Line 14.

**Comment by be-marc** [comment]
And require mlr3 0.21.1

**Comment by tdhock** [comment]
great thanks, I did that in https://github.com/tdhock/mlr3resampling/pull/18

is loaded_packages documented somewhere?

**Comment by be-marc** [comment]
Yes see https://mlr3.mlr-org.com/reference/mlr_reflections.html
