### ISSUE TITLE
Instantiated Resamplings

### ISSUE THREAD

**Issue by be-marc** [tdhock/mlr3resampling#19]
In the next mlr3 release we will enforce that instantiated resamplings can only be used with the task used during the instantiation.  

This does not work anymore:

```r
tsk_pima1 = tsk("pima", id = "pima1")
tsk_pima2 = tsk("pima", id = "pima2")

learner = lrn("classif.rpart")

resampling = rsmp("cv", folds = 3L)
resampling$instantiate(tsk_pima1)

grid = benchmark_grid(list(tsk_pima1, tsk_pima2), learner, resampling)

bmr = benchmark(grid, store_models = TRUE)
# | Error: Resampling 'cv' was not instantiated with task 'pima2'
```

That has to be done like this now:

```r
rsmp_cv1 = rsmp("cv", folds = 3L)
rsmp_cv1$instantiate(tsk_pima1)

rsmp_cv2 = rsmp("cv", folds = 3L)
rsmp_cv2$instantiate(tsk_pima2)

grid = benchmark_grid(list(tsk_pima1, tsk_pima2), learner, list(rsmp_cv1, rsmp_cv2), paired = TRUE)

bmr = benchmark(grid, store_models = TRUE)
```

The `Older_resamplers.Rmd` vignette fails with the new mlr3 version in line 873.

**Comment by tdhock** [comment]
Hi Marc, thanks for the report.
I understand that in the old/current version of mlr3, we are allowed to provide an un-instantiated learner with paired=FALSE. This is documented in ?benchmark_grid and I find this feature very convenient.
```
        * With 'paired' set to 'FALSE' (default), resampling strategies
          are not allowed to be instantiated, and instead will be
          instantiated per task internally. The only exception to this
```

You say that in the new version of mlr3, benchmark_grid must be called with paired=TRUE? This is of course possible but I feel like it would be less user-friendly. Can you please clarify the rationale for this change? or please explain how I can specify that I want to use a particular (un-instantiated) resampling method with all tasks? (like paired=FALSE in old mlr3)
